export const SceneKeys = {
  Title: 'Title',
  TitleNotice: 'TitleNotice',
  Loading: 'Loading',
  LoginBonus: 'LoginBonus',
  TitleEdit: 'TitleEdit',
  MainMenu: 'MainMenu',
  DebugBgm: 'DebugBgm',
  GridProblemEditor: 'GridProblemEditor',
  Story: 'Story',
  StoryList: 'StoryList',
  StoryCreator: 'StoryCreator',
  StoryPreview: 'StoryPreview',
  Transfer: 'Transfer',
  DailyMissions: 'DailyMissions',
  StageSelect: 'StageSelect',
  StageIntro: 'StageIntro',
  CaptureGame: 'CaptureGame',
  Result: 'Result',
  Evolution: 'Evolution',
  BattlePreview: 'BattlePreview',
  BattleSelect: 'BattleSelect',
  BattleGame: 'BattleGame',
  DexPreview: 'DexPreview',
  ShopPreview: 'ShopPreview',
  Achievements: 'Achievements',
} as const;
